name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        
    - name: Restore
      run: dotnet restore BB84.SAU.slnx
      
    - name: Build
      run: dotnet build BB84.SAU.slnx --no-restore --configuration release --verbosity minimal
      
    - name: Test
      run: dotnet test BB84.SAU.slnx --no-build --configuration release --verbosity minimal